/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts/ClientLogin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 客户端登录 (ClientLogin)
         * @description 返回纯文本格式，包含 `SID`, `LSID`, `Auth`。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description 用户名 */
                        Email: string;
                        /**
                         * Format: password
                         * @description API 密码
                         */
                        Passwd: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reader/api/0/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 CSRF Action Token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 57位字符的 Token 字符串 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reader/api/0/subscription/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取订阅列表 */
        get: {
            parameters: {
                query: {
                    output: "json";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功，包含 FreshRSS 优先级元数据 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            subscriptions?: components["schemas"]["Subscription"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reader/api/0/stream/contents/{streamId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取文章流内容
         * @description 支持流式响应和正文排除功能。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 返回数量，LLM 场景建议限制在 15-20 */
                    n?: number;
                    /** @description 排序。建议用 `o` (正序) 以支持滑动窗口补课逻辑 */
                    r?: "d" | "n" | "o";
                    /** @description 起始时间戳 (Unix Timestamp)，用于位移控制 */
                    ot?: number;
                    /** @description 排除目标，如 `user/-/state/com.google/read` (排除已读) */
                    xt?: string;
                    /** @description 是否排除正文和摘要（节省流量/Token） */
                    excludeContent?: boolean;
                    /** @description Continuation Token (分页) */
                    c?: string;
                };
                header?: never;
                path: {
                    /**
                     * @description Stream ID. 示例:
                     *     - `user/-/state/com.google/reading-list` (全部未读)
                     *     - `user/-/state/org.freshrss/important` (FreshRSS 重要文章)
                     *     - `user/-/label/MyLabel` (文件夹)
                     */
                    streamId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 流式 JSON 响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StreamResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reader/api/0/stream/items/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 根据 ID 批量获取文章内容 */
        post: {
            parameters: {
                query?: {
                    /** @description 是否排除正文 */
                    excludeContent?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description 文章 ID 列表 */
                        i: string[];
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StreamResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reader/api/0/edit-tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改文章状态（标记已读/星标）
         * @description 这是实现“处理完即标记已读”的核心接口
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description 文章 ID */
                        i: string[];
                        /** @description 添加标签（如 `user/-/state/com.google/read`） */
                        a?: string[];
                        /** @description 移除标签 */
                        r?: string[];
                        /** @description CSRF Token */
                        T: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Subscription: {
            id?: string;
            title?: string;
            url?: string;
            htmlUrl?: string;
            iconUrl?: string;
            /**
             * @description FreshRSS 优先级: important, main_stream, category, feed
             * @enum {string}
             */
            "frss:priority"?: "important" | "main_stream" | "category" | "feed";
        };
        StreamResponse: {
            id?: string;
            updated?: number;
            continuation?: string;
            items?: components["schemas"]["Item"][];
        };
        Item: {
            id?: string;
            title?: string;
            published?: number;
            canonical?: {
                href?: string;
            }[];
            alternate?: {
                href?: string;
            }[];
            summary?: {
                content?: string;
            };
            content?: {
                content?: string;
            };
            origin?: {
                streamId?: string;
                title?: string;
            };
            /** @description 显式输出的文章标签 */
            tags?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
