openapi: 3.0.3
info:
  title: FreshRSS Google Reader API (v4 Optimized)
  description: |
    基于 FreshRSS greader.php (v4 优化版) 源码生成的 Google Reader API 兼容层文档。
    
    **v4 版本核心改进**：
    - **流式输出 (Streaming)**：采用生成器模式，大幅降低处理大批量文章时的内存占用。
    - **Token 优化**：支持 `excludeContent` 参数，可排除文章正文，节省 LLM 消耗。
    - **FreshRSS 增强**：支持 `org.freshrss/important` 等优先级流，并在订阅列表中提供优先级元数据。
  version: 1.1.0
  contact:
    name: FreshRSS Team
    url: https://freshrss.org
servers:
  - url: /api/greader.php
    description: FreshRSS GReader API Endpoint

tags:
  - name: Auth
    description: 用户认证与令牌获取
  - name: Stream
    description: 文章流与内容获取
  - name: Subscription
    description: 订阅源(Feed)管理
  - name: Action
    description: 状态变更（已读、星标等）

security:
  - GoogleLoginAuth: []

paths:
  # ==========================================
  # Auth & Token
  # ==========================================
  /accounts/ClientLogin:
    post:
      tags:
        - Auth
      summary: 客户端登录 (ClientLogin)
      description: 返回纯文本格式，包含 `SID`, `LSID`, `Auth`。
      security: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required: [Email, Passwd]
              properties:
                Email: { type: string, description: 用户名 }
                Passwd: { type: string, format: password, description: API 密码 }
      responses:
        '200':
          description: 成功
          content:
            text/plain:
              schema:
                type: string
                example: "SID=...\nLSID=null\nAuth=..."

  /reader/api/0/token:
    get:
      tags:
        - Auth
      summary: 获取 CSRF Action Token
      responses:
        '200':
          description: 57位字符的 Token 字符串
          content:
            text/plain:
              schema: { type: string, minLength: 57 }

  # ==========================================
  # Subscriptions
  # ==========================================
  /reader/api/0/subscription/list:
    get:
      tags:
        - Subscription
      summary: 获取订阅列表
      parameters:
        - name: output
          in: query
          required: true
          schema: { type: string, enum: [json], default: json }
      responses:
        '200':
          description: 成功，包含 FreshRSS 优先级元数据
          content:
            application/json:
              schema:
                type: object
                properties:
                  subscriptions:
                    type: array
                    items: { $ref: '#/components/schemas/Subscription' }

  # ==========================================
  # Stream (Contents)
  # ==========================================
  /reader/api/0/stream/contents/{streamId}:
    get:
      tags:
        - Stream
      summary: 获取文章流内容
      description: 支持流式响应和正文排除功能。
      parameters:
        - name: streamId
          in: path
          required: true
          schema: { type: string }
          description: |
            Stream ID. 示例:
            - `user/-/state/com.google/reading-list` (全部未读)
            - `user/-/state/org.freshrss/important` (FreshRSS 重要文章)
            - `user/-/label/MyLabel` (文件夹)
        - name: n
          in: query
          description: 返回数量，LLM 场景建议限制在 15-20
          schema: { type: integer, default: 20 }
        - name: r
          in: query
          description: 排序。建议用 `o` (正序) 以支持滑动窗口补课逻辑
          schema: { type: string, enum: [d, n, o], default: d }
        - name: ot
          in: query
          description: 起始时间戳 (Unix Timestamp)，用于位移控制
          schema: { type: integer }
        - name: xt
          in: query
          description: 排除目标，如 `user/-/state/com.google/read` (排除已读)
          schema: { type: string }
        - name: excludeContent
          in: query
          description: 是否排除正文和摘要（节省流量/Token）
          schema: { type: boolean, default: false }
        - name: c
          in: query
          description: Continuation Token (分页)
          schema: { type: string }
      responses:
        '200':
          description: 流式 JSON 响应
          content:
            application/json:
              schema: { $ref: '#/components/schemas/StreamResponse' }

  /reader/api/0/stream/items/contents:
    post:
      tags:
        - Stream
      summary: 根据 ID 批量获取文章内容
      parameters:
        - name: excludeContent
          in: query
          description: 是否排除正文
          schema: { type: boolean }
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required: [i]
              properties:
                i: { type: array, items: { type: string }, description: 文章 ID 列表 }
      responses:
        '200':
          content:
            application/json:
              schema: { $ref: '#/components/schemas/StreamResponse' }

  # ==========================================
  # Actions
  # ==========================================
  /reader/api/0/edit-tag:
    post:
      tags:
        - Action
      summary: 修改文章状态（标记已读/星标）
      description: 这是实现“处理完即标记已读”的核心接口
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required: [i, T]
              properties:
                i: { type: array, items: { type: string }, description: 文章 ID }
                a: 
                  type: array
                  items: { type: string }
                  description: 添加标签（如 `user/-/state/com.google/read`）
                r: 
                  type: array
                  items: { type: string }
                  description: 移除标签
                T: { type: string, description: CSRF Token }
      responses:
        '200':
          description: OK
          content:
            text/plain: { schema: { type: string, example: OK } }

components:
  securitySchemes:
    GoogleLoginAuth:
      type: apiKey
      in: header
      name: Authorization
      description: "格式: GoogleLogin auth=YOUR_AUTH_TOKEN"

  schemas:
    Subscription:
      type: object
      properties:
        id: { type: string }
        title: { type: string }
        url: { type: string }
        htmlUrl: { type: string }
        iconUrl: { type: string }
        frss:priority:
          type: string
          description: "FreshRSS 优先级: important, main_stream, category, feed"
          enum: [important, main_stream, category, feed]

    StreamResponse:
      type: object
      properties:
        id: { type: string }
        updated: { type: integer }
        continuation: { type: string }
        items:
          type: array
          items: { $ref: '#/components/schemas/Item' }

    Item:
      type: object
      properties:
        id: { type: string }
        title: { type: string }
        published: { type: integer }
        canonical:
          type: array
          items: { type: object, properties: { href: { type: string } } }
        alternate:
          type: array
          items: { type: object, properties: { href: { type: string } } }
        # 以下字段在 excludeContent=true 时会被排除
        summary:
          type: object
          properties: { content: { type: string } }
        content:
          type: object
          properties: { content: { type: string } }
        origin:
          type: object
          properties: { streamId: { type: string }, title: { type: string } }
        tags:
          type: array
          items: { type: string }
          description: "显式输出的文章标签"